language: go

go:
  # This is the latest 1.x version of Go
  - "1.x"
  - "1.7"
  - "1.8"
  - "1.9"
  - "1.10"
  - "1.11"

before_install:
  - go get github.com/mattn/goveralls
  - go get golang.org/x/tools/cmd/cover

script:
  - $HOME/gopath/bin/goveralls -service=travis-ci
