language: go
go:
  # This is the latest 1.x version of Go
  - "1.x"
  - "1.7.x"
  - "1.8.x"
  - "1.9.x"
  - "1.10.x"
  - "1.11.x"
  - "1.12.x"
  - "1.13.x"
  - "1.14.x"
  - "1.15.x"
  - "1.16.x"
# Use Go modules for dependency management (https://github.com/golang/go/wiki/Modules)
env:
  - epubcheck_version=4.2.5
  - GO111MODULE=on
before_install:
  - wget https://github.com/IDPF/epubcheck/releases/download/v${epubcheck_version}/epubcheck-${epubcheck_version}.zip
  - unzip epubcheck-${epubcheck_version}.zip
  - go get github.com/mattn/goveralls
# This replaces the default script, which runs go test, because goveralls runs the entire test suite
script:
  - $HOME/gopath/bin/goveralls -service=travis-ci
