# Source: https://github.com/actions/starter-workflows/blob/main/ci/go.yml

name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  # Test with EPUBCheck and send test coverage
  test:
    runs-on: ubuntu-latest
    env:
      EPUBCHECK_VERSION: 4.2.5

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    # This needs to come after the checkout, which wipes the working directory
    - name: Download EPUBCheck
      run: |
        wget https://github.com/IDPF/epubcheck/releases/download/v${EPUBCHECK_VERSION}/epubcheck-${EPUBCHECK_VERSION}.zip
        unzip epubcheck-${EPUBCHECK_VERSION}.zip

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        # This is the latest 1.x version of Go
        go-version: 1.x

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v -coverprofile=profile.cov ./...

    - name: Send coverage
      uses: shogo82148/actions-goveralls@v1
      with:
        path-to-profile: profile.cov


  # Test with multiple versions of Go
  test-go-versions:
    runs-on: ubuntu-latest
    env:
      # TODO: I think we can get rid of this once we're no longer testing with Go < 1.13
      GO111MODULE: on
    strategy:
      matrix:
        # Test with the five most recent versions of Go; 1.x is the latest version (1.16)
        go: ['1.12', '1.13', '1.14', '1.15', '1.x']

    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go }}

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...
